### ISSUE TITLE
Bug in template

### ISSUE THREAD

**Issue by linuxscout** [openjournals/inara#17]
Hi, 
 I clone the repo, and try to test makefile on example paper
I got this errors:
```
~/workspace/tests/inara$ make ARTICLE=example/paper.md
INARA_ARTIFACTS_PATH=publishing-artifacts/ pandoc \
  --data-dir=data \
  --resource-path=.:resources:example/ \
  --metadata=article-info-file=resources/default-article-info.yaml \
  --variable=joss \
  --output=publishing-artifacts/paper.pdf \
  example/paper.md
"template" (line 388, column 16):
unexpected "{"
expecting "$endif$"
make: *** [Makefile:33: publishing-artifacts/paper.pdf] Error 5

```

**Comment by tarleb** [comment]
Thanks for the report. The most likely cause for this is an outdated pandoc version: newer versions allow to use `${varname}` instead of `$varname$` in templates. Can you try if [updating](https://github.com/jgm/pandoc/releases/latest) is enough to resolve the issue?

We should add a note about the minimal pandoc version in the docs.

**Comment by linuxscout** [comment]
Thank you, 
I Updated the package, and I passed this error.

Thanks

**Comment by tarleb** [comment]
Great, that's good to know. I've now added a short section on system requirements to the README.

**Comment by linuxscout** [comment]
I update the pandoc, but it was compiled with pandoc-citeproc 0.8.0.1 version, when the latest version is pandoc-citeproc 0.15.0.1

**Comment by tarleb** [comment]
Citation handling was changed sometime around pandoc 2.10, which now has a citeproc processor built-in. The pandoc-citeproc version should no longer matter for that reason.

**Comment by linuxscout** [comment]
Thank you.
